### ISSUE TITLE
Err 405 when using /login (README example)

### ISSUE THREAD

**Issue by YPares** [plow-technologies/servant-auth#21]
After building the README example and running it with `Cookie`, I'm running:

`curl -v -XPOST -H 'Content-Type: application/json' --data '{"username":"...", "password":"..."}' localhost:7249/login`

And getting:

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7249 (#0)
> POST /login HTTP/1.1
> Host: localhost:7249
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 40
> 
* upload completely sent off: 40 out of 40 bytes
< HTTP/1.1 405 Method Not Allowed
< Transfer-Encoding: chunked
< Date: Mon, 23 Jan 2017 14:01:43 GMT
< Server: Warp/3.2.8
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
Only GET or HEAD is supported
```

But the example **is** using PostNoContent for "/login"

Using:

  - servant-auth-server-0.2.1.0
  - servant-auth-0.2.1.0
  - jose-0.5.0.0

**Comment by jkarni** [comment]
I'm not sure exactly what the issue was, but I just tried this with version 0.2.3.0 and it correctly returns at 401. Can you confirm that this is fixed for you?

**Comment by jkarni** [comment]
Closing since it seems fixed.

**Comment by gleb-dianov** [comment]
Hi,

I have the same issue on 0.3.2.0

![screen shot 2018-08-06 at 22 57 44](https://user-images.githubusercontent.com/39841057/43743072-4ac913d8-99cc-11e8-88e6-7c11c930172b.png)
![screen shot 2018-08-06 at 22 58 25](https://user-images.githubusercontent.com/39841057/43743073-4adfa63e-99cc-11e8-86cc-5a00ae248472.png)

Any ideas on what might be the problem?
