### ISSUE TITLE
Support servant-server 0.10

### ISSUE THREAD

**Issue by 23Skidoo** [plow-technologies/servant-auth#33]
The latest version of `servant-auth-server` at the time of writing has a `>=0.9.1 && <0.10` constraint on `servant-server`. Would be nice if the latest version of `servant-server` (0.10) was supported.

**Comment by bugthunk** [comment]
Second that - especially since a lot more options for static file serving is delivered in `0.10` from what I can tell.

**Comment by jkarni** [comment]
Done in #34. Released as 0.2.6.0.

**Comment by 23Skidoo** [comment]
Thank you! That was fast.
