### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [plow-technologies/servant-auth#7]
The documentation for the latest version of this servant-auth-servant is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by jkarni** [comment]
I'm getting a 503 message from the hackage varnish cache (no clue why) when trying to upload. Will try again later.

**Comment by jkarni** [comment]
Done. The 503 was actually my doc script's fault.

**Comment by expipiplus1** [comment]
Thanks!
